# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1b3d84899ecc7206b0b89dc3e463e97fa32e7a3702198e3d1c9af0f193cc229b81520e36e9ce474dc904a7d40771e3bda5d67b2689894ed72bafd056d524405

test:
  secret_key_base: d4a8ef221e696cae6bbb6de3f45906f5fa540ccdffa9541bff4201ce1878decd95aa084123354f10ebaef893c92f6f4ac3ca187729615816fd91632d68093715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
